### ISSUE TITLE
bubble classroom template

### ISSUE THREAD

**Issue by ishita1209** [aydenbottos/Bubble-Plugin-Responsive-Voice-Text-to-Speech#1]
can you plz post the bubble classroom templete in your github with the full source code.It will be very helpful for my small college project.

**Comment by aydenbottos** [comment]
Sure, I will post my Google Classroom clone on GitHub.

Thanks,
Ayden Bottos



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
06/11/21,
09:53:17 AM
